/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedSolicitanteRouteImport } from './routes/_authenticated.solicitante'
import { Route as AuthenticatedTecnicoRouteImport } from './routes/_authenticated.tecnico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitanteRoute =
  AuthenticatedSolicitanteRouteImport.update({
    id: '/solicitante',
    path: '/solicitante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTecnicoRoute = AuthenticatedTecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitante': typeof AuthenticatedSolicitanteRoute
  '/tecnico': typeof AuthenticatedTecnicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitante': typeof AuthenticatedSolicitanteRoute
  '/tecnico': typeof AuthenticatedTecnicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/solicitante': typeof AuthenticatedSolicitanteRoute
  '/_authenticated/tecnico': typeof AuthenticatedTecnicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/solicitante' | '/tecnico'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/solicitante' | '/tecnico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/solicitante'
    | '/_authenticated/tecnico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitante': {
      id: '/_authenticated/solicitante'
      path: '/solicitante'
      fullPath: '/solicitante'
      preLoaderRoute: typeof AuthenticatedSolicitanteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnico': {
      id: '/_authenticated/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof AuthenticatedTecnicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSolicitanteRoute: typeof AuthenticatedSolicitanteRoute
  AuthenticatedTecnicoRoute: typeof AuthenticatedTecnicoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSolicitanteRoute: AuthenticatedSolicitanteRoute,
  AuthenticatedTecnicoRoute: AuthenticatedTecnicoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
